"use client";

import * as React from "react";
import { Sparkles } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CopyButton } from "@/components/common/copy-button";
import { DownloadButton } from "@/components/common/download-button";
import { EmptyState } from "@/components/common/empty-state";
import { cn } from "@/lib/utils";

export interface OutputBlock {
  title: string;
  text: string;
}

export interface GeneratorResult {
  ok: boolean;
  mode?: "template" | "ai";
  tool?: string;
  blocks?: OutputBlock[];
  raw?: string;
  error?: string;
}

/**
 * Generic output panel for every text generator: renders titled blocks,
 * copies everything or per block, downloads a .txt, shows the mode
 * (Free template vs AI-provider) honestly.
 */
export function OutputCard({
  result,
  message,
  onRegenerate,
  fileName,
  className,
}: {
  result: GeneratorResult | null;
  message?: string;
  onRegenerate?: () => void;
  fileName?: string;
  className?: string;
}) {
  const blocks = result?.blocks ?? [];
  const raw = result?.raw ?? blocks.map((b) => b.text).join("\n\n");

  if (!result) {
    return (
      <EmptyState
        title={message ?? "No content generated yet."}
        message="Enter your topic and click Generate."
      />
    );
  }

  if (!result.ok) {
    return null;
  }

  return (
    <Card className={cn("border-border", className)}>
      <CardContent className="space-y-4 p-5">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <Sparkles className="size-4 text-primary" />
            <span className="text-sm font-medium text-foreground">
              Generated content
            </span>
            <Badge variant={result.mode === "ai" ? "success" : "secondary"}>
              {result.mode === "ai" ? "AI provider" : "Free template"}
            </Badge>
          </div>
          <div className="flex flex-wrap gap-2">
            <CopyButton text={raw} />
            <DownloadButton filename={fileName ?? "output.txt"} text={raw} />
            {onRegenerate ? (
              <Button type="button" variant="secondary" size="sm" onClick={onRegenerate}>
                Regenerate
              </Button>
            ) : null}
          </div>
        </div>

        {blocks.length > 0 ? (
          <div className="space-y-4">
            {blocks.map((b, i) => (
              <div key={i} className="rounded-md border border-border bg-muted/25 p-4">
                <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
                  <h4 className="text-sm font-semibold text-foreground">
                    {b.title}
                  </h4>
                  <CopyButton text={b.text} label="Copy" className="h-7 px-2 text-xs" />
                </div>
                <pre className="whitespace-pre-wrap font-sans text-sm leading-6 text-foreground/90">
                  {b.text}
                </pre>
              </div>
            ))}
          </div>
        ) : null}

        {result.mode === "template" ? (
          <p className="text-xs text-muted-foreground">
            Generated by the built-in free template engine. Configure an AI
            provider in Settings to upgrade to AI-powered output.
          </p>
        ) : null}
      </CardContent>
    </Card>
  );
}