import { env } from "@/lib/ai/env";
import { badRequest, clientIp, json } from "@/lib/api/generate-route";
import { rateLimit } from "@/lib/ai/ratelimit";
import { getImageProviderFor } from "@/lib/ai/image";
import type {
  ImageGenerationInput,
  ImageGenerationResult,
} from "@/lib/ai/types";

const STYLES: Record<string, string> = {
  realistic: "natural photo, soft daylight",
  cinematic: "cinematic mood, dramatic light",
  anime: "anime art, clean lines",
  "3d": "3d render, studio light",
  pixar: "pixar style, cute",
  illustration: "painterly illustration",
  "digital-art": "digital art, concept art",
  fantasy: "fantasy scene, mystical glow",
  christian: "serene, reverent atmosphere",
  nature: "nature scene, vivid colors",
  product: "studio product shot, clean backdrop",
  portrait: "portrait, shallow depth of field",
  thumbnail: "bold thumbnail, high contrast, minimal",
};

const RATIOS: Record<string, [number, number]> = {
  "1:1": [1024, 1024],
  "16:9": [1280, 720],
  "9:16": [720, 1280],
  "4:3": [1024, 768],
};

/** Script names used when baking selected-language text onto the image. */
const LANG_WORDS: Record<string, string> = {
  en: "",
  te: "in Telugu script",
  hi: "in Hindi script",
  ta: "in Tamil script",
  kn: "in Kannada script",
  ml: "in Malayalam script",
};

/**
 * Build an optional "text on the image" overlay phrase. Kept short (120 chars)
 * so the composed prompt stays inside the provider's limit. English renders
 * best with image models; other scripts are best-effort — the UI says so.
 */
function buildOverlayPhrase(text: string, textLang: string): string {
  const overlay = text.trim().slice(0, 120);
  if (!overlay) return "";
  const langWord = LANG_WORDS[textLang];
  return `, large bold text${langWord ? ` ${langWord}` : ""} on the image reading "${overlay}"`;
}

export async function POST(req: Request) {
  const rl = rateLimit(`img:${clientIp(req)}`, env.rateLimitMax, env.rateLimitWindowMs);
  if (!rl.ok) {
    return json({ ok: false, error: "Too many requests. Try again shortly." }, 429);
  }

  let parsed: unknown;
  try {
    parsed = await req.json();
  } catch {
    return badRequest("Invalid JSON body.");
  }
  const p = (parsed ?? {}) as Record<string, unknown>;
  const prompt = typeof p.prompt === "string" ? p.prompt.slice(0, 1500).trim() : "";
  if (!prompt) return badRequest("`prompt` is required.");

  const style = typeof p.style === "string" ? p.style : "realistic";
  const ratio = typeof p.ratio === "string" ? p.ratio : "1:1";
  const size = RATIOS[ratio] ?? RATIOS["1:1"];
  const negative = typeof p.negative === "string" ? p.negative.slice(0, 500) : "";
  const text = typeof p.text === "string" ? p.text : "";
  const textLang = typeof p.textLang === "string" ? p.textLang : "en";
  const overlayPhrase = buildOverlayPhrase(text, textLang);

  const baseStyled = STYLES[style] ? `${prompt}, ${STYLES[style]}` : prompt;
  const styledPrompt = `${baseStyled}${overlayPhrase}`.slice(0, 1000);

  const input: ImageGenerationInput = {
    prompt: styledPrompt,
    negativePrompt: negative || "text, watermark, logo, low quality, blurry",
    width: size[0],
    height: size[1],
    seed: typeof p.seed === "number" ? p.seed : undefined,
    model: typeof p.model === "string" ? p.model : undefined,
  };

  // Engine override from the tool's "Image engine" picker.
  const requested = typeof p.provider === "string" ? p.provider.trim() : "";
  const providerId = ["gemini", "huggingface", "pollinations", "local", "none"].includes(
    requested,
  )
    ? requested
    : env.imageProvider;

  const ENGINE_NAMES: Record<string, string> = {
    gemini: "Gemini (Nano Banana)",
    huggingface: "Hugging Face",
    pollinations: "Pollinations",
    local: "local Stable Diffusion",
    none: "disabled",
  };

  const provider = getImageProviderFor(providerId);
  let result: ImageGenerationResult;
  let notice: string | undefined;

  if (!provider.configured) {
    // The selected engine has no credentials on this server — use the
    // always-free engine and say exactly why.
    const fb = getImageProviderFor("pollinations");
    const fbResult = await fb.generate(input);
    if (fbResult.ok) {
      notice = `The ${ENGINE_NAMES[providerId] ?? providerId} image engine isn't configured on this server — this image was generated by the free Pollinations service instead.`;
      result = fbResult;
    } else {
      result = {
        ok: false,
        provider: providerId,
        error: `The ${ENGINE_NAMES[providerId] ?? providerId} image engine isn't configured, and the free fallback also failed: ${fbResult.error}`,
      };
    }
  } else {
    result = await provider.generate(input);

    // Honest fallback: never dead-end. If the chosen engine fails, try the
    // always-free Pollinations service and label the swap clearly.
    if (!result.ok && provider.id !== "pollinations") {
      const fb = getImageProviderFor("pollinations");
      const fbResult = await fb.generate(input);
      if (fbResult.ok) {
        notice = `The ${ENGINE_NAMES[provider.id] ?? provider.id} image engine failed (${result.error}) — this image was generated by the free Pollinations service instead.`;
        result = fbResult;
      } else {
        result = {
          ...result,
          error: `${result.error} (Pollinations fallback also failed: ${fbResult.error})`,
        };
      }
    }

    // Some free services (Pollinations) occasionally 500 on specific style
    // keywords while the same prompt works un-styled. Retry once with the raw
    // prompt so the user still gets an image instead of a dead end.
    if (
      !result.ok &&
      /500/.test(String(result.error)) &&
      styledPrompt !== prompt
    ) {
      result = await provider.generate({
        ...input,
        prompt: `${prompt}${overlayPhrase}`.slice(0, 1000),
      });
    }
  }

  return json(notice ? { ...result, notice } : result);
}